import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import { SideBar } from '@/app/components/SideBar';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-full`}
			>
				<div id="modal" />
				<div className={'flex h-full'}>
					<SideBar />
					<main className="w-full pt-4 flex flex-col items-center">
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
